version: '2'
services:

  #  The Application
  app:
    image: rakshans1/laravel-react
    working_dir: /var/www
    volumes:
      - /var/www/storage
    env_file: '.env.prod'
    ports:
      - 80:8080
  # The Web Server
  # web:
  #   image: rakshans1/laravel-react-web
    # volumes:
    #   - "${LE_DIR}:/etc/letsencrypt"
    # ports:
    #   - 80:80
    #   - 443:443

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

  # redis
  # cache:
  #   image: redis:3.0-alpine

volumes:
  dbdata:
